/** Curated `@phosphor-icons/react` import surface for the picker.
 *
 *  Why named imports: `import * as Ph from "@phosphor-icons/react"`
 *  defeats tree-shaking and pulls all ~3000 icons. Named imports here
 *  let webpack/turbopack keep only the curated subset.
 *
 *  KEEP IN SYNC with `phosphor-catalog.ts`. */

import type { Icon } from "@phosphor-icons/react";
import {
  Alarm,
  Archive,
  ArrowBendUpLeft,
  ArrowDown,
  ArrowDownRight,
  ArrowLeft,
  ArrowRight,
  ArrowSquareOut,
  ArrowUp,
  ArrowUpRight,
  Asterisk,
  At,
  Bell,
  Binary,
  Book,
  BookOpen,
  Bookmark,
  Books,
  BracketsCurly,
  BracketsRound,
  BracketsSquare,
  Briefcase,
  Bug,
  Buildings,
  Calculator,
  Calendar,
  CalendarBlank,
  CalendarCheck,
  Camera,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  ChartBar,
  ChartBarHorizontal,
  ChartLine,
  ChartPie,
  ChatCircle,
  ChatText,
  Check,
  CheckSquare,
  Circle,
  Clipboard,
  ClipboardText,
  Clock,
  Cloud,
  CloudArrowDown,
  CloudArrowUp,
  CloudLightning,
  CloudRain,
  CloudSnow,
  Code,
  Coins,
  Columns,
  Compass,
  Cpu,
  CreditCard,
  Crop,
  Crosshair,
  Crown,
  CurrencyDollar,
  Database,
  DeviceMobile,
  DeviceTablet,
  Diamond,
  Disc,
  Divide,
  DownloadSimple,
  Drop,
  Envelope,
  Equals,
  Eraser,
  Eye,
  EyeSlash,
  Eyedropper,
  FastForward,
  File,
  FileCode,
  FileText,
  FilmStrip,
  Flag,
  Flame,
  Flower,
  FlowArrow,
  Folder,
  FolderOpen,
  Funnel,
  Gear,
  GitBranch,
  GitCommit,
  GitMerge,
  GitPullRequest,
  GithubLogo,
  Globe,
  GridFour,
  Hammer,
  Handshake,
  HardDrives,
  Hash,
  Headphones,
  Heart,
  Hexagon,
  Highlighter,
  Hourglass,
  House,
  Image,
  Images,
  Info,
  Kanban,
  Key,
  Laptop,
  Lightning,
  Link,
  List,
  ListBullets,
  ListChecks,
  ListPlus,
  Lock,
  LockOpen,
  MagicWand,
  Magnet,
  MagnifyingGlass,
  MapPin,
  MapTrifold,
  Megaphone,
  Memory,
  Microphone,
  Microscope,
  Minus,
  Money,
  Monitor,
  Moon,
  Mountains,
  MusicNote,
  Network,
  Notebook,
  NotePencil,
  Package,
  PaintBrush,
  Palette,
  PaperPlaneTilt,
  Paperclip,
  Pause,
  Pencil,
  PencilLine,
  Percent,
  Phone,
  PhoneCall,
  Plant,
  Play,
  Plus,
  Pulse,
  PushPin,
  Question,
  Radio,
  Rainbow,
  Receipt,
  Rewind,
  Rows,
  Ruler,
  Scissors,
  ShareNetwork,
  ShoppingBag,
  ShoppingCart,
  Sigma,
  SkipBack,
  SkipForward,
  Sliders,
  Snowflake,
  Sparkle,
  SpeakerHigh,
  SpeakerSimpleHigh,
  Square,
  Stack,
  Star,
  Storefront,
  Sun,
  SunHorizon,
  Table,
  Tag,
  Target,
  Television,
  Timer,
  Tornado,
  Tray,
  Trash,
  Tree,
  TreeEvergreen,
  TrendDown,
  TrendUp,
  Triangle,
  Trophy,
  UploadSimple,
  User,
  UserCircle,
  UserMinus,
  UserPlus,
  Users,
  VideoCamera,
  Wallet,
  Wind,
  Wrench,
  X,
} from "@phosphor-icons/react";

export const PHOSPHOR_ICONS: Readonly<Record<string, Icon>> = {
  Alarm, Archive, ArrowBendUpLeft, ArrowDown, ArrowDownRight, ArrowLeft, ArrowRight,
  ArrowSquareOut, ArrowUp, ArrowUpRight, Asterisk, At, Bell, Binary, Book, BookOpen,
  Bookmark, Books, BracketsCurly, BracketsRound, BracketsSquare, Briefcase, Bug,
  Buildings, Calculator, Calendar, CalendarBlank, CalendarCheck, Camera, CaretDown,
  CaretLeft, CaretRight, CaretUp, ChartBar, ChartBarHorizontal, ChartLine, ChartPie,
  ChatCircle, ChatText, Check, CheckSquare, Circle, Clipboard, ClipboardText, Clock,
  Cloud, CloudArrowDown, CloudArrowUp, CloudLightning, CloudRain, CloudSnow, Code,
  Coins, Columns, Compass, Cpu, CreditCard, Crop, Crosshair, Crown, CurrencyDollar,
  Database, DeviceMobile, DeviceTablet, Diamond, Disc, Divide, DownloadSimple, Drop,
  Envelope, Equals, Eraser, Eye, EyeSlash, Eyedropper, FastForward, File, FileCode,
  FileText, FilmStrip, Flag, Flame, Flower, FlowArrow, Folder, FolderOpen, Funnel,
  Gear, GitBranch, GitCommit, GitMerge, GitPullRequest, GithubLogo, Globe, GridFour,
  Hammer, Handshake, HardDrives, Hash, Headphones, Heart, Hexagon, Highlighter,
  Hourglass, House, Image, Images, Info, Kanban, Key, Laptop, Lightning, Link, List,
  ListBullets, ListChecks, ListPlus, Lock, LockOpen, MagicWand, Magnet, MagnifyingGlass,
  MapPin, MapTrifold, Megaphone, Memory, Microphone, Microscope, Minus, Money, Monitor,
  Moon, Mountains, MusicNote, Network, Notebook, NotePencil, Package, PaintBrush,
  Palette, PaperPlaneTilt, Paperclip, Pause, Pencil, PencilLine, Percent, Phone,
  PhoneCall, Plant, Play, Plus, Pulse, PushPin, Question, Radio, Rainbow, Receipt,
  Rewind, Rows, Ruler, Scissors, ShareNetwork, ShoppingBag, ShoppingCart, Sigma,
  SkipBack, SkipForward, Sliders, Snowflake, Sparkle, SpeakerHigh, SpeakerSimpleHigh,
  Square, Stack, Star, Storefront, Sun, SunHorizon, Table, Tag, Target, Television,
  Timer, Tornado, Tray, Trash, Tree, TreeEvergreen, TrendDown, TrendUp, Triangle,
  Trophy, UploadSimple, User, UserCircle, UserMinus, UserPlus, Users, VideoCamera,
  Wallet, Wind, Wrench, X,
};

export type PhosphorIconName = keyof typeof PHOSPHOR_ICONS;

export { FileText as FallbackPhosphorIcon };

export function resolvePhosphorIcon(name: string): Icon | null {
  return PHOSPHOR_ICONS[name] ?? null;
}
