import type { Page } from "@/shared/types/domain";
import { NOW, idSeed } from "./profile";
import { TASKS_DB_ID, taskRow } from "./tasksDb";

export function seedPages(): Page[] {
  return [
    {
      id: idSeed("getting-started"),
      parentId: null,
      title: "Getting Started",
      icon: "👋",
      cover: "linear-gradient(135deg, hsl(24 90% 70%), hsl(340 80% 70%))",
      favorite: true,
      trashed: false,
      createdAt: NOW - 1000 * 60 * 60 * 24 * 7,
      updatedAt: NOW - 1000 * 60 * 60,
      blocks: [
        { id: "b1", type: "h1", text: "Welcome to your workspace" },
        { id: "b2", type: "paragraph", text: "This is a quiet, focused place to think, write and ship. Use the sidebar to navigate, press / inside any block for the slash menu." },
        { id: "b3", type: "callout", text: "Tip: press ⌘K (or Ctrl K) to search across every page." },
        { id: "b4", type: "h2", text: "Try these things" },
        { id: "b5", type: "todo", text: "Click a block and press / to insert headings, todos, code", checked: true },
        { id: "b6", type: "todo", text: "Drag the • handle on the left to reorder blocks", checked: false },
        { id: "b7", type: "todo", text: "Star a page to pin it to Favorites", checked: false },
        { id: "b8", type: "divider", text: "" },
        { id: "b9", type: "quote", text: "Simplicity is the ultimate sophistication. — da Vinci" },
      ],
    },
    {
      id: idSeed("projects"),
      parentId: null,
      title: "Projects",
      icon: "🚀",
      favorite: true,
      trashed: false,
      createdAt: NOW - 1000 * 60 * 60 * 24 * 5,
      updatedAt: NOW - 1000 * 60 * 60 * 2,
      blocks: [
        { id: "p1", type: "h1", text: "Projects" },
        { id: "p2", type: "paragraph", text: "An overview of what's in flight this quarter." },
        { id: "p3", type: "h3", text: "Current focus" },
        { id: "p4", type: "bullet", text: "Launch the marketing site refresh" },
        { id: "p5", type: "bullet", text: "Ship onboarding v2 with sample workspaces" },
        { id: "p6", type: "bullet", text: "Performance audit across editor surfaces" },
        { id: "p7", type: "h2", text: "Task tracker" },
        { id: "p8", type: "database", text: "", databaseId: TASKS_DB_ID },
      ],
    },
    {
      id: idSeed("orbit"),
      parentId: idSeed("projects"),
      title: "Orbit – marketing site",
      icon: "🛰️",
      favorite: false,
      trashed: false,
      createdAt: NOW - 1000 * 60 * 60 * 24 * 4,
      updatedAt: NOW - 1000 * 60 * 30,
      blocks: [
        { id: "o1", type: "h1", text: "Orbit" },
        { id: "o2", type: "paragraph", text: "A new marketing site that explains the product in 30 seconds." },
        { id: "o3", type: "h3", text: "Milestones" },
        { id: "o4", type: "todo", text: "Brand exploration", checked: true },
        { id: "o5", type: "todo", text: "Hero section copy", checked: true },
        { id: "o6", type: "todo", text: "Pricing page", checked: false },
        { id: "o7", type: "todo", text: "Launch", checked: false },
        { id: "o8", type: "code", text: "npm run deploy --env=production", lang: "bash" },
      ],
    },
    {
      id: idSeed("onboarding"),
      parentId: idSeed("projects"),
      title: "Onboarding v2",
      icon: "🪄",
      favorite: false,
      trashed: false,
      createdAt: NOW - 1000 * 60 * 60 * 24 * 3,
      updatedAt: NOW - 1000 * 60 * 60 * 6,
      blocks: [
        { id: "n1", type: "h1", text: "Onboarding v2" },
        { id: "n2", type: "quote", text: "First impressions decide whether the second one happens." },
        { id: "n3", type: "paragraph", text: "We replace the empty workspace with a curated starter that shows the best the product has to offer." },
      ],
    },
    {
      id: idSeed("notes"),
      parentId: null,
      title: "Notes",
      icon: "📚",
      favorite: false,
      trashed: false,
      createdAt: NOW - 1000 * 60 * 60 * 24 * 2,
      updatedAt: NOW - 1000 * 60 * 10,
      blocks: [
        { id: "x1", type: "h1", text: "Notes" },
        { id: "x2", type: "paragraph", text: "Stray thoughts and reading highlights." },
        { id: "x3", type: "bullet", text: "Read: Designing for the long term" },
        { id: "x4", type: "bullet", text: "Watch: How small teams ship faster" },
      ],
    },
    {
      id: idSeed("reading"),
      parentId: idSeed("notes"),
      title: "Reading list",
      icon: "📖",
      favorite: false,
      trashed: false,
      createdAt: NOW - 1000 * 60 * 60 * 24,
      updatedAt: NOW - 1000 * 60 * 5,
      blocks: [
        { id: "r1", type: "h1", text: "Reading list" },
        { id: "r2", type: "todo", text: "The Beginning of Infinity – Deutsch", checked: false },
        { id: "r3", type: "todo", text: "Working in Public – Eghbal", checked: true },
      ],
    },
    // Database rows (each is a Page with rowOfDatabaseId)
    taskRow("row_t1", "Brand exploration", "opt_done", "opt_med", "2026-04-15", true, 1000 * 60 * 60 * 24 * 6),
    taskRow("row_t2", "Pricing page draft", "opt_doing", "opt_high", "2026-05-02", false, 1000 * 60 * 60 * 24 * 3),
    taskRow("row_t3", "Hero copy revisions", "opt_doing", "opt_med", "2026-05-04", false, 1000 * 60 * 60 * 24 * 2),
    taskRow("row_t4", "Launch checklist", "opt_todo", "opt_high", "2026-05-10", false, 1000 * 60 * 60 * 24 * 1),
    taskRow("row_t5", "Post-launch retro", "opt_todo", "opt_low", "2026-05-20", false, 1000 * 60 * 60 * 12),
  ];
}
